# Generated by Django 4.0.6 on 2022-08-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post2_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='id',
        ),
        migrations.AlterField(
            model_name='post2',
            name='page_url',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
